"""
ESG Report Generator - Content Generation Engine (Environment Chapter)
"""
import re

# Try to import anthropic, but don't fail if not available (for test mode)
try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False
    print("  ⚠ Warning: anthropic module not available. Test mode will be used.")

from config import ANTHROPIC_API_KEY, CLAUDE_MODEL


class ContentEngine:
    """Generate Environment Chapter Report Content Using Claude"""

    def __init__(self, test_mode=False, company_profile=None, api_key=None):
        self.test_mode = test_mode
        self.company_profile = company_profile or {}
        
        # Use provided API Key, otherwise use config's
        actual_api_key = api_key or ANTHROPIC_API_KEY
        
        if not test_mode and actual_api_key and ANTHROPIC_AVAILABLE:
            try:
                self.client = anthropic.Anthropic(api_key=actual_api_key)
                print(f"  ✓ ContentEngine initialized (API Key: {actual_api_key[:10]}...)")
            except Exception as e:
                print(f"  ✗ ContentEngine initialization failed: {e}")
                print(f"  ⚠ Falling back to test mode")
                self.client = None
                self.test_mode = True  # Force test mode if API fails
        else:
            self.client = None
            if test_mode:
                print("  ✓ Test mode: Skipping API calls, using placeholder text")
            elif not ANTHROPIC_AVAILABLE:
                print("  ⚠ Warning: anthropic module not available, using test mode")
                self.test_mode = True  # Force test mode if module not available
            elif not actual_api_key:
                print("  ⚠ Warning: API Key not provided, using test mode")
                self.test_mode = True  # Force test mode if no API key
    
    def _get_company_context(self):
        """Get company size background description"""
        if not self.company_profile:
            return ""
        
        size = self.company_profile.get("size", "Small and Medium")
        revenue = self.company_profile.get("revenue_display", "Unknown")
        budget = self.company_profile.get("budget_display", "Unknown")
        
        return f"""
Company Size Background:
- Company Size: {size} Enterprise
- Estimated Annual Revenue: {revenue}
- Recommended Energy-Saving Investment Budget: {budget}
Please adjust the description tone and recommended amounts based on this size.
"""

    def _clean_llm_output(self, text):
        """Clean meta-instructions and tags from LLM output"""
        if not text:
            return text
        
        # Define patterns to remove from the beginning (Chinese and English)
        patterns_to_remove = [
            r'^以下是.*?[：:]\s*',           # 以下是...：
            r'^以下為.*?[：:]\s*',           # 以下為...：
            r'^这是.*?[：:]\s*',             # 这是...：
            r'^這是.*?[：:]\s*',             # 這是...：
            r'^內容如下.*?[：:]\s*',         # 內容如下：
            r'^内容如下.*?[：:]\s*',         # 内容如下：
            r'^Here is the.*?[：:]\s*',     # Here is the...
            r'^Here\'s the.*?[：:]\s*',     # Here's the...
            r'^The following is.*?[：:]\s*', # The following is...
            r'^Below is.*?[：:]\s*',         # Below is...
            r'^以下.*?[：:]\s*',             # 以下：
            r'^\【.*?\】\s*',                # 【說明】
            r'^「.*?」\s*',                  # 「標題」
            r'^\*\*.*?\*\*\s*',              # **標題**
            r'^##\s+.*?\n',                  # ## 標題
            r'^#\s+.*?\n',                   # # 標題
        ]
        
        # Apply each cleaning pattern
        cleaned_text = text
        for pattern in patterns_to_remove:
            cleaned_text = re.sub(pattern, '', cleaned_text, flags=re.IGNORECASE | re.MULTILINE)
        
        # Remove leading and trailing whitespace
        cleaned_text = cleaned_text.strip()
        
        # Remove multiple consecutive line breaks (keep at most one blank line)
        cleaned_text = re.sub(r'\n{3,}', '\n\n', cleaned_text)
        
        return cleaned_text

    def generate(self, prompt, max_tokens=1000):
        """Call Claude API and clean output"""
        # Test mode: return placeholder text
        if self.test_mode:
            return "[Test Mode] This is where LLM-generated content will appear. During actual execution, professional ESG report content will be generated by Claude API. Our company is committed to sustainable development and actively implements environmental protection policies."
        
        # Check if client is initialized
        if not self.client:
            if not ANTHROPIC_AVAILABLE:
                return "[Test Mode] anthropic module not available. Please install it with: pip install anthropic"
            error_msg = "[Content Generation Failed: API Key not provided or client not initialized]"
            print(f"✗ {error_msg}")
            return error_msg
        
        try:
            message = self.client.messages.create(
                model=CLAUDE_MODEL,
                max_tokens=max_tokens,
                messages=[{
                    "role": "user",
                    "content": prompt
                }]
            )
            # ✅ Clean output before returning
            raw_text = message.content[0].text
            cleaned_text = self._clean_llm_output(raw_text)
            return cleaned_text
        except Exception as e:
            error_msg = f"[Content Generation Failed: {e}]"
            print(f"✗ Claude API Error: {e}")
            print(f"  ⚠ Falling back to test mode placeholder text")
            return "[Test Mode] API call failed. This is placeholder text for testing purposes."

    # ==================== Environment Chapter Content Generation Methods ====================

    def generate_environmental_cover(self, config):
        """Environmental Chapter Cover Introduction - 50-70 words (for right text box)"""
        prompt = """Write 50-70 words for the ESG report environmental chapter introduction, including: climate change challenges, corporate environmental responsibility, sustainability commitments, and TCFD establishment. Use a professional and warm tone. Use "we" and "our company" instead of third-person expressions like "this company" or "the enterprise". Keep it concise and impactful."""
        return self.generate(prompt, max_tokens=300)

    def generate_sustainability_committee(self, config):
        """Sustainability Committee Organizational Structure Description - 140-160 words (including company size)"""
        company_context = self._get_company_context()
        # Get annual revenue information (including Arabic numerals)
        revenue_display = self.company_profile.get("revenue_display", "Unknown")
        prompt = f"""Write 140-160 words describing the sustainability committee organizational structure diagram, including: committee establishment purpose, importance of organizational structure, meeting frequency, cross-departmental collaboration mechanisms, policy formulation and crisis management. Use a professional tone. Use first-person expressions like "we" and "our company".
Our company's annual revenue is approximately {revenue_display}.
{company_context}
Please adjust the description based on company size. For example, small and medium-sized enterprises can emphasize "streamlined and efficient organizational structure," while medium-sized enterprises can emphasize "comprehensive cross-departmental collaboration"."""
        return self.generate(prompt, max_tokens=600)

    def generate_policy_description(self, config):
        """Environmental Policy Four Dimensions Description - 140-160 words"""
        prompt = """Write 140-160 words describing the environmental policy four dimensions pie chart, including: policy formulation philosophy, discussion of four-dimensional risk monitoring, risk definition, significance and importance of risk assessment and response, and overall environmental strategy. Use first-person expressions like "we" and "our company"."""
        return self.generate(prompt, max_tokens=600)

    def generate_tcfd_financial_disclosure(self, config):
        """4.3 TCFD Climate-Related Financial Disclosure Description - 140-160 words"""
        company_context = self._get_company_context()
        prompt = f"""Write 140-160 words for the ESG report describing TCFD climate-related financial disclosure, including:
1. TCFD framework introduction and importance
2. Climate risk and opportunity identification methods
3. Company's commitment to adopting TCFD and specific actions
4. Potential impact of climate risks on finances

Use a professional tone, use first-person expressions like "our company" and "we".
{company_context}
Please adjust the description based on company size. For example, small and medium-sized enterprises can emphasize "gradually establishing TCFD management mechanisms," while medium-sized enterprises can emphasize "comprehensive TCFD risk assessment system"."""
        return self.generate(prompt, max_tokens=600)

    def generate_tcfd_matrix_analysis(self, config):
        """TCFD Risk Matrix Analysis - 140-160 words"""
        prompt = """Write 140-160 words of detailed description for the TCFD risk matrix diagram, including: purpose and significance of the matrix diagram including rising market customer preference for sustainable products, which is a brand premium opportunity; B2B customers' increasing ESG requirements leading to more collaboration and supply chain integration opportunities; impact severity and probability assessment criteria such as cost pressures, climate change leading to increased energy costs, carbon tax impacts, etc.; priority judgment mechanisms, and risk management strategies. Use first-person expressions like "we" and "our company"."""
        return self.generate(prompt, max_tokens=600)

    def generate_ghg_calculation_method(self, config):
        """Carbon Emission Calculation Method Description - 140-160 words"""
        prompt = """Write 140-160 words describing the carbon emission data table, including: definitions of the three greenhouse gas scopes, GHG Protocol calculation standards, estimation methods for each scope, data collection where electricity consumption multiplied by industry coefficients accounts for over 90% of total carbon emissions, and should comply with GRI requirements. Use first-person expressions like "we" and "our company"."""
        return self.generate(prompt, max_tokens=600)

    def generate_electricity_policy(self, config):
        """Electricity Usage and Energy Conservation Policy - 140-160 words"""
        prompt = """Write 140-160 words describing electricity usage and energy conservation policy, including: importance of electricity in carbon emissions, general energy-saving measures, energy management policies, and strategies for improving electricity usage efficiency. Use first-person expressions like "we" and "our company"."""
        return self.generate(prompt, max_tokens=600)

    def generate_energy_efficiency_measures(self, config):
        """Energy Efficiency Measures Description - 140-160 words (including investment budget recommendations)"""
        company_context = self._get_company_context()
        
        # Get specific budget figures and annual revenue information (including Arabic numerals)
        budget_display = self.company_profile.get("budget_display", "appropriate")
        revenue_display = self.company_profile.get("revenue_display", "Unknown")
        
        prompt = f"""Write 140-160 words describing energy efficiency measures, including: LED smart lighting systems, smart air conditioning control, building ventilation optimization, and other energy-saving technology applications and benefits. Use first-person expressions like "we" and "our company".
Our company's annual revenue is approximately {revenue_display}.
{company_context}
Please mention specific investment plans in the text, for example, "Our company plans to invest approximately {budget_display} in energy-saving equipment updates," and explain expected benefits (such as energy-saving rate, investment payback period). Ensure recommended amounts are appropriate for company size."""
        return self.generate(prompt, max_tokens=600)

    def generate_green_planting_program(self, config):
        """Green Planting Program Description - 50-70 words (for right text box)"""
        prompt = """Write 50-70 words describing the green planting program, including: SDGs biodiversity goals, importance of ecological diversity, forest adoption and restoration plans, and benefits of green factory planting. Use first-person expressions like "we" and "our company". Keep it concise and impactful."""
        return self.generate(prompt, max_tokens=300)

    def generate_water_management(self, config):
        """Water Resource Management Description - 140-160 words"""
        prompt = """Write 140-160 words describing water resource management, including: importance of water resource environmental protection, water conservation plan measures, water usage efficiency improvement, and water resource recycling strategies. Use first-person expressions like "we" and "our company"."""
        return self.generate(prompt, max_tokens=600)

    def generate_waste_management(self, config):
        """Waste Management Description - 140-160 words"""
        prompt = """Write 140-160 words describing waste management, including: waste classification and treatment, circular economy concepts, waste reduction measures, and resource recycling and reuse processes. Use first-person expressions like "we" and "our company"."""
        return self.generate(prompt, max_tokens=600)

    def generate_environmental_education(self, config):
        """Environmental Education and Cooperation Description - 50-70 words (for right text box)"""
        prompt = """Write 50-70 words describing environmental education and cooperation, including: student education camp activities, employee family day environmental advocacy, wetland ecology recording plans, and community environmental cooperation projects. Use first-person expressions like "we" and "our company". Keep it concise and impactful."""
        return self.generate(prompt, max_tokens=300)

    def generate_sasb_analysis(self, config, industry, sasb_code, sasb_name):
        """SASB Industry Classification Analysis - 150-170 words"""
        company_context = self._get_company_context()
        revenue_display = self.company_profile.get("revenue_display", "Unknown")
        
        prompt = f"""You are an ESG expert. Conduct a SASB analysis for the "{industry}" industry and write 150-170 words.

【Industry Information】
- Industry Name: {industry}
- SASB Code: {sasb_code}
- SASB Industry Category: {sasb_name}
- Our company's annual revenue is approximately {revenue_display}.
{company_context}

From an ESG expert's perspective, for the "{industry}" industry (SASB Classification: {sasb_name}):
1. Analyze the key ESG issues for this industry under the SASB framework
2. From SASB common issues, propose 5 most relevant improvement recommendations for this industry classification
3. Based on company size and industry characteristics, explain the priority order and implementation focus of these recommendations

Please clearly list 5 recommendations and explain why these issues are particularly important for the "{industry}" industry.

Use a professional tone, use first-person expressions like "we" and "our company". Keep it concise within 150-170 words."""
        return self.generate(prompt, max_tokens=600)